pipeline {
    
    tools {
        allure 'Allure Report'
    }
    
    agent {
        label 'linux'
    }

    stages {
    
        stage('Setup Parameters') {
            steps {
                script { 
                    properties([
                        parameters([
                            string(
                                defaultValue: 'tests/test_pass.py', 
                                name: 'TESTS', 
                                trim: true
                            ),
                            string(
                                defaultValue: """--test-log-level=INFO --db-host=mariadb --alluredir=artifacts/allure-results
                                """,
                                name: 'PYTEST_ARGS', 
                                trim: true
                            ),
                            string(
                                defaultValue: 'http://opencart:8080', 
                                name: 'BASE_URL', 
                                trim: true
                            ),
                            choice (
                                name: 'BROWSER',
                                choices: 'chromium\nfirefox\nwebkit',
                                defaultValue: 'chromium'
                            ),
                            booleanParam (
                                name: 'HEADED',
                                defaultValue: false,
                                description: 'Run browser in headed mode'
                            ),
                            // string(
                            //     defaultValue: '', 
                            //     name: 'BROWSER_VERSION', 
                            //     trim: true
                            // ),
                            string(
                                defaultValue: '1', 
                                name: 'THREADS', 
                                trim: true
                            )
                        ])
                    ])
                }
            }
        }
        
        stage('Checkout') {
            steps {
                git branch: 'main',url: 'https://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@github.com/Alive08/otus-qa-playwright.git'
            }
        }
        
        stage('Setup Environment') {
            steps {
                sh """#!/bin/bash
                rm -rf ./artifacts
                mkdir -p ./artifacts
                chmod 777 ./artifacts
                """
            }
        }
    
        stage('Run Tests') {
            steps {
                sh """#!/bin/bash
                [ ${params.HEADED} == "true" ] && headed="--headed" || headed=""
                ./run_tests_compose.sh \
                \${headed} \
                --browser=${params.BROWSER} \
                --base-url=${params.BASE_URL} \
                -n ${params.THREADS} \
                ${params.PYTEST_ARGS} \
                ${params.TESTS}
                """
            }
            
            post {
                always {
                    allure includeProperties: false, jdk: '', report: 'artifacts/allure-report', results: [[path: 'artifacts/allure-results']]
                    archiveArtifacts artifacts: 'artifacts/*.log', allowEmptyArchive: 'true'
                    archiveArtifacts artifacts: 'artifacts/screenshots/**/*.png', allowEmptyArchive: 'true'
                }
            }
        }
    }
}
